### ISSUE TITLE
Having some problem deploying this to Heroku.

### ISSUE THREAD

**Issue by adisaneadi** [rtunazzz/atc-server#2]
remote: -----> Running: go install -v -tags heroku -mod=vendor github.com/bonzayio/go-atc-server
remote: github.com/go-chi/chi
remote: # github.com/go-chi/chi
remote: vendor/github.com/go-chi/chi/tree.go:60:20: invalid operation: 2 << n (shift count type int, must be unsigned integer)
remote:  !     Push rejected, failed to compile Go app.
remote:
remote:  !     Push failed
remote: Verifying deploy...

Getting this error, would you know what is causing this? To me, this looks like an error with the dependency, not sure, didn't get this running locally.

Very new to Go and control, and was using your source code to post ATC requests to cart products on local retailers.

**Comment by rtunazzz** [comment]
Hi, seems like you're using a wrong version of Go for heroku. Can you check which one are you using?
